name: Azure Function CI/CD

on:
  push:
    paths:
      - 'visitor-api/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd visitor-api
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        cd visitor-api
        python -m unittest test_main.py

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: visitorcounterjace-automated
        package: ./visitor-api
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
