name: Deploy Frontend to Azure Static Website

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name azurercloudesume \
            --destination '$web' \
            --source ./frontend \
            --auth-mode key \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Purge Azure Front Door cache
      run: |
        az network front-door purge-endpoint \
          --resource-group azureresume \
          --name resume-jace-gzbwhagnbdc5cdfg \
          --content-paths '/*'
