name: Deploy Frontend to Azure Static Website

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name <STORAGE_ACCOUNT_NAME> \
            --destination '$web' \
            --source ./frontend \
            --auth-mode key \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }}
