name: Deploy Frontend to Azure Static Website

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show contents of frontend before upload
      run: |
        echo "📁 frontend directory structure:"
        ls -R ./frontend
        echo "📄 index.html preview:"
        head -n 15 ./frontend/index.html || echo "index.html not found"

    - name: Upload to Azure Storage
      uses: azure/cli@v1
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name azurercloudesume \
            --destination '$web' \
            --source ./frontend \
            --overwrite true \
            --auth-mode key \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Purge Azure Front Door cache (AFD Standard)
      run: |
        az afd endpoint purge \
          --resource-group azureresume \
          --profile-name HTTPS \
          --endpoint-name resume-jace-gzbwhagnbdc5cdfg \
          --content-paths '/*'

